<?php
echo '<!DOCTYPE html>';
echo '<html lang="ar" dir="rtl">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>مملكة السرد</title>';
echo '<link rel="icon" href="Website.jpg">';
echo '<link rel="stylesheet" href="style.css">';
echo '</head>';
echo '<body>';
echo '<aside class="aside-page">';
echo '<h1>';
echo '<img src="Website.jpg" alt="صورة الموقع" height="50" width="50">';
echo '<sup>مملكة السرد</sup>';
echo '</h1>';
echo '<div class="category-box">';
echo '<ul>';
echo '<li><a href="comedy.php"><div class="category-title">Comedy</div></a></li>';
echo '<li><a href="science_fiction.php"><div class="category-title">Science Fiction</div></a></li>';
echo '<li><a href="fantasy.php"><div class="category-title">Fantasy</div></a></li>';
echo '<li><a href="romance.php"><div class="category-title">Romance</div></a></li>';
echo '<li><a href="crime_investigation.php"><div class="category-title">Crime and Investigation</div></a></li>';
echo '<li><a href="horror.php"><div class="category-title">Horror</div></a></li>';
echo '<li><a href="adventure.php"><div class="category-title">Adventure</div></a></li>';
echo '<li><a href="drama.php"><div class="category-title">Drama</div></a></li>';
echo '<li><a href="historical.php"><div class="category-title">Historical</div></a></li>';
echo '<li><a href="heist.php"><div class="category-title">Heist</div></a></li>';
echo '<li><a href="war.php"><div class="category-title">War</div></a></li>';
echo '</ul>';
echo '</div>';
echo '<section id="story-list">';
echo '<h2>أحدث القصص</h2>';
echo '<ul>';
echo '<li>';
echo '<a href="story1.html">';
echo '<h1 style="color: black;">قلب العنقاء</h1>';
echo '</a>';
echo '<dd style="color: black;">امير يحارب في صحراء لا نهائية للحصول على قلب العنقاء للملك</dd>';
echo '<li>';
echo '<a href="story2.html">';
echo '<h1 style="color: black;">كين و سيد التنانين</h1>';
echo '</a>';
echo '<dd style="color: black;">طفل يكشف كهف سيد التنانين و سره الاخطر</dd>';
echo '</li>';
echo '<li>';
echo '<a href="story3.html">';
echo '<h1 style="color: black;">ذكرياتي</h1>';
echo '</a>';
echo '<dd style="color: black;">احدث قصة تعرف على ذكرياتي بعالم متطور و مستقبلي</dd>';
echo '</li>';
echo '</ul>';
echo '</section>';
echo '</aside>';
echo '</body>';
echo '</html>';
?>